- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install basic utilities
  apt:
    name: [git, curl, htop]
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
  when: ansible_os_family == "Debian"

- name: Enable UFW firewall
  ufw:
    state: enabled
    policy: deny
  when: ansible_os_family == "Debian"

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
  when: ansible_os_family == "Debian"

- name: Install basic utilities (Windows)
  win_chocolatey:
    name:
      - git
      - notepadplusplus
      - googlechrome
    state: present
  when: ansible_os_family == "Windows"

- name: Ensure Windows Defender feature is installed
  win_feature:
    name: Windows-Defender-Features
    state: present
  when: ansible_os_family == "Windows"