- name: Download and install the CloudWatch agent
  shell: |
    wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
    dpkg -i amazon-cloudwatch-agent.deb
  when: ansible_os_family == "Debian"

- name: Configure CloudWatch agent (Linux)
  template:
    src: cloudwatch-config.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
  when: ansible_os_family == "Debian"