name: AMI Automation Pipeline

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ami-pipeline.yml"
      - "packer/**"
      - "ansible/**"
      - "terraform/**"

jobs:
  stage-1-packer:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - name: Stage 1 - Packer :- Building Golden AMIs
        run: echo "🟢 Stage 1 :- Packer - Building Golden AMIs with preconfigured services"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: "latest"

      - name: Install Packer Amazon plugin
        run: |
          packer plugins install github.com/hashicorp/amazon

      - name: Install Packer Ansible plugin
        run: |
          packer plugins install github.com/hashicorp/ansible
          
      - name: Check Packer Version and Plugins
        run: |
          packer version
          packer plugins installed
          
      - name: Run Packer Validate
        run: |
          packer validate packer/linux-base.json

      - name: Build Linux AMI
        run: |
          packer build packer/linux-base.json

  stage-2-terraform:
    runs-on: ubuntu-latest
    needs: stage-1-packer
    steps:
      - name: Stage 2 - Terraform :- Deploy AMIs
        run: echo "🟢 Stage 2 :- Terraform - Deploy AMIs (scaffold step)"

  stage-3-cicd:
    runs-on: ubuntu-latest
    needs: stage-2-terraform
    steps:
      - name: Stage 3 - CI/CD :- Orchestration
        run: echo "🟢 Stage 3:- CI/CD Automation with GitHub Actions (scaffold step)"

  stage-4-security:
    runs-on: ubuntu-latest
    needs: stage-3-cicd
    steps:
      - name: Stage 4 - Security and Best Practices
        run: echo "🟢 Stage 4:- Security and Best Practices (scaffold step)"

  stage-5-final-outcome:
    runs-on: ubuntu-latest
    needs: stage-4-security
    steps:
      - name: Stage 5 - Final Outcome & Review
        run: echo "✅ Stage 5:- Final Outcome – Pipeline complete (scaffold step)"